backend:
  name: git-gateway
  branch: main

media_folder: "dna-astro/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Eventi"
    folder: "dna-astro/src/content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine", name: "cover", widget: "image" }
      - { label: "Descrizione", name: "body", widget: "markdown" }