backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "events"
    label: "Eventi"
    folder: "events"
    create: true
    format: "json"
    extension: "json"

    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Link Foto", name: "galleryLink", widget: "string", required: false }